/*
 * TRAKTOR
 * Copyright (c) 2026 Anders Pistol.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */
#pragma once

#include "Core/Timer/Timer.h"
#include "Render/ITexture.h"
#include "Render/Frame/RenderGraphTypes.h"
#include "Resource/Proxy.h"

// import/export mechanism.
#undef T_DLLCLASS
#if defined(T_WORLD_EXPORT)
#	define T_DLLCLASS T_DLLEXPORT
#else
#	define T_DLLCLASS T_DLLIMPORT
#endif

namespace traktor::render
{

class IRenderSystem;
class RenderContext;
class RenderGraph;
class Shader;

}

namespace traktor::world
{

/*! Compute-driven texture.
 * \ingroup World
 *
 * A texture whose contents are generated by a compute shader.
 * Implements ITexture so it can be used as a regular texture
 * asset by any material or shader. The compute dispatch
 * is performed via the render graph during world setup.
 */
class T_DLLCLASS ComputeTexture : public render::ITexture
{
	T_RTTI_CLASS;

public:
	bool create(
		render::IRenderSystem* renderSystem,
		const resource::Proxy< render::Shader >& shader,
		int32_t width,
		int32_t height,
		render::TextureFormat format,
		bool continuous
	);

	virtual void destroy() override final;

	virtual Size getSize() const override final;

	virtual int32_t getBindlessIndex() const override final;

	virtual bool lock(int32_t side, int32_t level, Lock& lock) override final;

	virtual void unlock(int32_t side, int32_t level) override final;

	virtual ITexture* resolve() override final;

	void setup(render::RenderGraph& renderGraph);

	bool isContinuous() const { return m_continuous; }

private:
	resource::Proxy< render::Shader > m_shader;
	Ref< ITexture > m_texture;
	Timer m_timer;
	int32_t m_width = 0;
	int32_t m_height = 0;
	bool m_continuous = true;
	bool m_generated = false;
};

}
