#define TOKEN_OPEN                             1
#define TOKEN_LEFT_PARANTHESIS                 2
#define TOKEN_SEMICOLON                        3
#define TOKEN_UNTIL                            4
#define TOKEN_DO                               5
#define TOKEN_END                              6
#define TOKEN_WHILE                            7
#define TOKEN_REPEAT                           8
#define TOKEN_IF                               9
#define TOKEN_FUNCTION                        10
#define TOKEN_EQUAL                           11
#define TOKEN_FOR                             12
#define TOKEN_NAME                            13
#define TOKEN_IN                              14
#define TOKEN_ELSE                            15
#define TOKEN_ELSEIF                          16
#define TOKEN_THEN                            17
#define TOKEN_BREAK                           18
#define TOKEN_RETURN                          19
#define TOKEN_LOCAL                           20
#define TOKEN_LESS                            21
#define TOKEN_CONST                           22
#define TOKEN_GREATER                         23
#define TOKEN_COLON                           24
#define TOKEN_DOT                             25
#define TOKEN_COMMA                           26
#define TOKEN_OR                              27
#define TOKEN_AND                             28
#define TOKEN_LESS_EQUAL                      29
#define TOKEN_GREATER_EQUAL                   30
#define TOKEN_EQUAL_EQUAL                     31
#define TOKEN_NOT_EQUAL                       32
#define TOKEN_DOT_DOT                         33
#define TOKEN_PLUS                            34
#define TOKEN_MINUS                           35
#define TOKEN_MULTIPLY                        36
#define TOKEN_DIVIDE                          37
#define TOKEN_MODULO                          38
#define TOKEN_NOT                             39
#define TOKEN_HASH                            40
#define TOKEN_RAISE                           41
#define TOKEN_NIL                             42
#define TOKEN_TRUE                            43
#define TOKEN_FALSE                           44
#define TOKEN_NUMBER                          45
#define TOKEN_STRING                          46
#define TOKEN_DOT_DOT_DOT                     47
#define TOKEN_BITWISE_OR                      48
#define TOKEN_BITWISE_AND                     49
#define TOKEN_LEFT_BRACKET                    50
#define TOKEN_RIGHT_BRACKET                   51
#define TOKEN_RIGHT_PARANTHESIS               52
#define TOKEN_LEFT_BRACE                      53
#define TOKEN_RIGHT_BRACE                     54
