/*
 * TRAKTOR
 * Copyright (c) 2026 Anders Pistol.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */
#pragma once

#include <list>
#include <map>
#include <string>

#include "Core/Containers/AlignedVector.h"
#include "Core/Math/Vector4.h"
#include "Mesh/Editor/MeshPipelineTypes.h"
#include "Render/ITexture.h"
#include "Resource/Id.h"
#include "World/WorldTypes.h"

namespace traktor::model
{

class Model;

}

namespace traktor::mesh
{

/*! Provenance of a generated ray tracing vertex.
 *
 * A vertex produced by the clipping/tessellation lies within a single source
 * triangle; its attributes are the barycentric blend of the triangle's vertices.
 * This lets a converter reconstruct attributes the generic builder doesn't emit,
 * e.g. skinning weights.
 */
struct RayTracingVertexSource
{
	uint32_t vertices[3];	//!< Model vertex indices of the source triangle.
	float weights[3];		//!< Barycentric weights within the source triangle.
};

/*! Ray tracing geometry generated from a model.
 *
 * Surfaces which use an alpha tested material are clipped ("cut") and
 * tessellated to their diffuse coverage mask so only triangles which actually
 * have coverage remain; this way the ray tracing shaders never need to perform
 * any alpha testing themselves.
 *
 * The geometry is expressed as a flat triangle soup which is meant to be
 * appended after the model's own (raster) geometry into the same vertex and
 * index buffers:
 *  - Indices strictly less than the model's vertex count reference the model's
 *    own vertices (unmodified surfaces).
 *  - Indices greater or equal reference \a extraPositions, i.e. vertices which
 *    were generated by the clipping/tessellation.
 *  - \a materials holds one HWRT_Material per index (triangle corner), laid out
 *    to match the acceleration structure primitive order (primitive*3 + corner).
 */
struct RayTracingGeometry
{
	AlignedVector< Vector4 > extraPositions;
	AlignedVector< RayTracingVertexSource > extraVertexSources;	//!< Provenance of each generated vertex, parallel to \a extraPositions (for deriving deformable attributes such as skin weights).
	AlignedVector< uint32_t > indices;
	AlignedVector< world::HWRT_Material > materials;
};

/*! Build ray tracing geometry from a model, cutting alpha tested surfaces to their coverage mask.
 *
 * \param model Source model.
 * \param materialTechniqueMap Map from model material name to techniques (drives iteration order and which materials are included).
 * \param baseVertexCount Number of vertices which precede the generated geometry in the destination vertex buffer (i.e. the model's own vertex count).
 * \param outAlbedoTextures Collected albedo texture references, indexed by HWRT_Material::albedoMap.
 * \param outGeometry Generated ray tracing geometry.
 */
void buildRayTracingGeometry(
	const model::Model* model,
	const std::map< std::wstring, std::list< MeshMaterialTechnique > >& materialTechniqueMap,
	uint32_t baseVertexCount,
	AlignedVector< resource::Id< render::ITexture > >& outAlbedoTextures,
	RayTracingGeometry& outGeometry);

}
