/*
 * TRAKTOR
 * Copyright (c) 2026 Anders Pistol.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */
#pragma once

#include <list>
#include <map>
#include <string>

#include "Core/Containers/AlignedVector.h"
#include "Core/Math/Vector4.h"
#include "Mesh/Editor/MeshPipelineTypes.h"
#include "Render/ITexture.h"
#include "Resource/Id.h"
#include "World/WorldTypes.h"

namespace traktor::model
{

class Model;

}

namespace traktor::mesh
{

/*! Ray tracing geometry packaged from a model.
 *
 * Alpha tested surfaces have already been cut ("clipped") to their coverage mask by the
 * CutAlpha model operation, so the ray tracing shaders never need to alpha test. This just
 * flattens the (cut) model into a triangle soup meant to be appended after the model's own
 * (raster) geometry into the same vertex and index buffers:
 *  - Indices strictly less than \a baseVertexCount reference vertices the ray tracing model
 *    shares with the raster mesh (its unchanged prefix), so those are not duplicated.
 *  - Indices greater or equal reference \a extraPositions, i.e. the model's remaining vertices
 *    (the ones generated by cutting, or - when the ray tracing model was reduced independently -
 *    all of its vertices).
 *  - \a materials holds one HWRT_Material per index (triangle corner), laid out to match the
 *    acceleration structure primitive order (primitive*3 + corner).
 */
struct RayTracingGeometry
{
	AlignedVector< Vector4 > extraPositions;
	AlignedVector< uint32_t > indices;
	AlignedVector< world::HWRT_Material > materials;
};

/*! Package ray tracing geometry from a (already cut) model.
 *
 * \param model Ray tracing model; alpha tested surfaces are assumed already cut (see CutAlpha).
 * \param materialTechniqueMap Map from model material name to techniques (drives iteration order and which materials are included).
 * \param rasterVertexCount Number of raster vertices preceding the ray tracing geometry in the destination vertex buffer; \a extraPositions are appended after these.
 * \param sharedVertexCount Number of leading model vertices that ARE those raster vertices (referenced in place); the rest are emitted as \a extraPositions. Equals \a rasterVertexCount when the model only shares the raster prefix (cut but not otherwise modified), and 0 when the model was rebuilt (e.g. reduced) and needs its own vertex set.
 * \param outAlbedoTextures Collected albedo texture references, indexed by HWRT_Material::albedoMap.
 * \param outGeometry Generated ray tracing geometry.
 */
void buildRayTracingGeometry(
	const model::Model* model,
	const std::map< std::wstring, std::list< MeshMaterialTechnique > >& materialTechniqueMap,
	uint32_t rasterVertexCount,
	uint32_t sharedVertexCount,
	AlignedVector< resource::Id< render::ITexture > >& outAlbedoTextures,
	RayTracingGeometry& outGeometry);

}
