<?xml version="1.0" encoding="utf-8"?>
<object type="ddc.DfnImport">
	<module>Standard</module>
	<next type="ddc.DfnImport">
		<module>Traktor</module>
		<next type="ddc.DfnImport">
			<module>Traktor</module>
			<next type="ddc.DfnImport">
				<module>Traktor</module>
				<next type="ddc.DfnImport">
					<module>Traktor</module>
					<next type="ddc.DfnNamespace">
						<name>parade</name>
						<statements type="ddc.DfnClass">
							<access>AccPrivate</access>
							<name>StageData</name>
							<super/>
							<members type="ddc.DfnMember">
								<type type="ddc.DfnType">
									<name>LayerData</name>
									<subst/>
									<isArray>true</isArray>
									<range>0</range>
									<next/>
								</type>
								<name>layers</name>
								<next/>
							</members>
							<next type="ddc.DfnClass">
								<access>AccPrivate</access>
								<name>LayerData</name>
								<super/>
								<members type="ddc.DfnMember">
									<type type="ddc.DfnType">
										<name>string</name>
										<subst/>
										<isArray>false</isArray>
										<range>0</range>
										<next/>
									</type>
									<name>name</name>
									<next/>
								</members>
								<next type="ddc.DfnClass">
									<access>AccPrivate</access>
									<name>FlashLayerData</name>
									<super>LayerData</super>
									<members type="ddc.DfnMember">
										<type type="ddc.DfnType">
											<name>traktor</name>
											<subst/>
											<isArray>false</isArray>
											<range>0</range>
											<next/>
										</type>
										<name>resource</name>
										<next type="ddc.DfnMember">
											<type type="ddc.DfnType">
												<name>traktor</name>
												<subst/>
												<isArray>false</isArray>
												<range>0</range>
												<next/>
											</type>
											<name>Ref</name>
											<next type="ddc.DfnMember">
												<type type="ddc.DfnType">
													<name>traktor</name>
													<subst/>
													<isArray>false</isArray>
													<range>0</range>
													<next/>
												</type>
												<name>Ref</name>
												<next type="ddc.DfnMember">
													<type type="ddc.DfnType">
														<name>std</name>
														<subst/>
														<isArray>false</isArray>
														<range>0</range>
														<next/>
													</type>
													<name>vector</name>
													<next/>
												</next>
											</next>
										</next>
									</members>
									<next type="ddc.DfnClass">
										<access>AccPrivate</access>
										<name>SceneLayerData</name>
										<super>LayerData</super>
										<members type="ddc.DfnMember">
											<type type="ddc.DfnType">
												<name>traktor</name>
												<subst/>
												<isArray>false</isArray>
												<range>0</range>
												<next/>
											</type>
											<name>resource</name>
											<next/>
										</members>
										<next/>
									</next>
								</next>
							</next>
						</statements>
						<next/>
					</next>
				</next>
			</next>
		</next>
	</next>
</object>
