// THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT!

#include "Core/Serialization/ISerializer.h"
#include "Core/Serialization/Member.h"
#include "Test/Parade.h"

namespace parade
{

T_IMPLEMENT_RTTI_FACTORY_CLASS("StageData", 0, StageData, traktor::ISerializable)

bool StageData::serialize(traktor::ISerializer& s)
{
	s >> traktor::Member< LayerData >("layers", m_layers);
	return true;
}

T_IMPLEMENT_RTTI_FACTORY_CLASS("LayerData", 0, LayerData, traktor::ISerializable)

bool LayerData::serialize(traktor::ISerializer& s)
{
	s >> traktor::Member< string >("name", m_name);
	return true;
}

T_IMPLEMENT_RTTI_FACTORY_CLASS("FlashLayerData", 0, FlashLayerData, traktor::ISerializable)

bool FlashLayerData::serialize(traktor::ISerializer& s)
{
	s >> traktor::Member< traktor >("resource", m_resource);
	s >> traktor::Member< traktor >("Ref", m_Ref);
	s >> traktor::Member< traktor >("Ref", m_Ref);
	s >> traktor::Member< std >("vector", m_vector);
	return true;
}

T_IMPLEMENT_RTTI_FACTORY_CLASS("SceneLayerData", 0, SceneLayerData, traktor::ISerializable)

bool SceneLayerData::serialize(traktor::ISerializer& s)
{
	s >> traktor::Member< traktor >("resource", m_resource);
	return true;
}

}

