// THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT!

#ifndef INCLUDE_8F8471F3_E93A_264A_93AB_5C7B41CEF429_H
#define INCLUDE_8F8471F3_E93A_264A_93AB_5C7B41CEF429_H

#include "Core/Serialization/ISerializable.h"

namespace parade
{

class StageData : public traktor::ISerializable
{
	T_RTTI_CLASS;

public:
	virtual bool serialize(traktor::ISerializer& s);

private:
};

class LayerData : public traktor::ISerializable
{
	T_RTTI_CLASS;

public:
	virtual bool serialize(traktor::ISerializer& s);

private:
};

class FlashLayerData : public traktor::ISerializable
{
	T_RTTI_CLASS;

public:
	virtual bool serialize(traktor::ISerializer& s);

private:
};

class SceneLayerData : public traktor::ISerializable
{
	T_RTTI_CLASS;

public:
	virtual bool serialize(traktor::ISerializer& s);

private:
};

}

#endif	// INCLUDE_8F8471F3_E93A_264A_93AB_5C7B41CEF429_H
