#include "Render/OpenGL/Std/Platform.h"

namespace traktor
{
	namespace render
	{

std::wstring getOpenGLErrorString(GLenum glError)
{
	switch (glError)
	{
	case GL_NO_ERROR:
		return L"GL_NO_ERROR";
	case GL_INVALID_ENUM:
		return L"GL_INVALID_ENUM";
	case GL_INVALID_VALUE:
		return L"GL_INVALID_VALUE";
	case GL_INVALID_OPERATION:
		return L"GL_INVALID_OPERATION";
	case GL_INVALID_FRAMEBUFFER_OPERATION:
		return L"GL_INVALID_FRAMEBUFFER_OPERATION";
	case GL_OUT_OF_MEMORY:
		return L"GL_OUT_OF_MEMORY";
	case GL_FRAMEBUFFER_UNDEFINED:
		return L"GL_FRAMEBUFFER_UNDEFINED";
	case GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT:
		return L"GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT";
	case GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT:
		return L"GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT";
	case GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER:
		return L"GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER";
	case GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER:
		return L"GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER";
	case GL_FRAMEBUFFER_UNSUPPORTED:
		return L"GL_FRAMEBUFFER_UNSUPPORTED";
	case GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE:
		return L"GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE";
	case GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS:
		return L"GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS";
	}
	return L"Unknown GL error";
}

	}
}
